development:
  adapter: postgresql
  encoding: unicode
  database: lootly_development
  pool: 5
  username: rtaff2012
  password: leonruss
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: lootly_development
  pool: 5
  username: rtaff2012
  password: leonruss
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: lootly_development
  pool: 5
  username: rtaff2012
  password: leonruss
  host: localhost